"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Must be set before the first migrate. Changing it after auth tables exist
# breaks every FK that points at auth.User, including admin.LogEntry.
AUTH_USER_MODEL = "onboarding.User"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "onboarding",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# `manage.py test` only forces settings.DEBUG to False after this module has
# already been imported and INSTALLED_APPS already built, so checking DEBUG
# alone here would still install the toolbar under `.env`'s DEBUG=True and
# fail debug_toolbar's own test-environment check. sys.argv is checked
# directly instead.
TESTING = "test" in sys.argv
DEBUG_TOOLBAR_ENABLED = DEBUG and not TESTING

if DEBUG_TOOLBAR_ENABLED:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

INTERNAL_IPS = ["127.0.0.1"]

# show_toolbar_with_docker also falls back to resolving the Docker host's IP,
# unlike the plain show_toolbar callback most tutorials wire up, which only
# checks INTERNAL_IPS and never renders from inside a container.
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": "debug_toolbar.middleware.show_toolbar_with_docker",
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

# Every error response is translated to {"message": ..., "extra": {}} in one
# place, so services and selectors just raise ApplicationError or a normal
# DRF/Django exception and never build a Response for an error themselves.
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "api.exception_handlers.exception_handler",
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# Cache
# https://docs.djangoproject.com/en/6.0/topics/cache/

CACHES = {
    "default": env.cache("REDIS_URL"),
}


# Celery
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html

# The Celery app in config/celery.py, the worker service, and the result
# backend decision all come later. This setting exists now so the broker is
# configured from the environment like every other connection URL, and so the
# Redis database split is recorded in one place. See .env.example for why the
# broker and the cache do not share a database number.
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")


# Embeddings
# https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

# The model name and its output dimension are settings constants, not values
# hardcoded in onboarding/embeddings.py, so both live in one place. This does
# not make swapping providers a config change: the dimension is baked into
# Skill.embedding's VectorField at the database level, so a different model
# still needs a migration and a re-embed of every row.
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
EMBEDDING_DIMENSIONS = 384
