"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import sys
from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False),
)
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS", default=[])

# Must be set before the first migrate. Changing it after auth tables exist
# breaks every FK that points at auth.User, including admin.LogEntry.
AUTH_USER_MODEL = "onboarding.User"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "onboarding",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# `manage.py test` only forces settings.DEBUG to False after this module has
# already been imported and INSTALLED_APPS already built, so checking DEBUG
# alone here would still install the toolbar under `.env`'s DEBUG=True and
# fail debug_toolbar's own test-environment check. sys.argv is checked
# directly instead.
TESTING = "test" in sys.argv
DEBUG_TOOLBAR_ENABLED = DEBUG and not TESTING

if DEBUG_TOOLBAR_ENABLED:
    INSTALLED_APPS += ["debug_toolbar"]
    MIDDLEWARE += ["debug_toolbar.middleware.DebugToolbarMiddleware"]

INTERNAL_IPS = ["127.0.0.1"]

# show_toolbar_with_docker also falls back to resolving the Docker host's IP,
# unlike the plain show_toolbar callback most tutorials wire up, which only
# checks INTERNAL_IPS and never renders from inside a container.
DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": "debug_toolbar.middleware.show_toolbar_with_docker",
}

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/

# Every error response is translated to {"message": ..., "extra": {}} in one
# place, so services and selectors just raise ApplicationError or a normal
# DRF/Django exception and never build a Response for an error themselves.
REST_FRAMEWORK = {
    "EXCEPTION_HANDLER": "api.exception_handlers.exception_handler",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    # Every endpoint requires a caller by default. An endpoint that is meant
    # to stay open needs its own explicit AllowAny, which none do today.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.ScopedRateThrottle",
    ],
    # Only the token-obtain view declares a throttle_scope today. Simple
    # JWT's UPDATE_LAST_LOGIN writes to the database on every successful
    # login, and the docs call that out as a potential DoS vector without a
    # throttle in front of it.
    "DEFAULT_THROTTLE_RATES": {
        "token_obtain": "5/min",
    },
}

# https://django-rest-framework-simplejwt.readthedocs.io/en/stable/settings.html

# SIGNING_KEY is deliberately its own environment variable rather than a
# reuse of SECRET_KEY (see .env.example). Rotating JWT_SIGNING_KEY
# invalidates every outstanding token pair without touching anything else
# derived from SECRET_KEY, such as signed cookies or password reset tokens.
SIMPLE_JWT = {
    # Short enough that a leaked access token is only useful for a few
    # minutes, long enough that a normal API session isn't spending most of
    # its traffic on refresh calls.
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    # A hire who logs in once in the morning stays logged in through the day
    # without needing to re-enter credentials.
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    # Rotation issues a new refresh token on every use; blacklisting rejects
    # the one it replaced. Rotation alone still leaves a stolen refresh
    # token usable right up until its natural expiry, since nothing marks
    # the old one as spent, so the two settings are paired deliberately.
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "SIGNING_KEY": env("JWT_SIGNING_KEY"),
    "UPDATE_LAST_LOGIN": True,
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": env.db("DATABASE_URL"),
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"


# Cache
# https://docs.djangoproject.com/en/6.0/topics/cache/

# env.cache() infers BACKEND from whether django_redis is importable, so
# adding an unrelated package that pulls it in transitively could silently
# switch backends. BACKEND is pinned here to Django's built-in RedisCache
# instead of trusting that resolution order.
CACHES = {
    "default": env.cache("REDIS_URL"),
}
CACHES["default"]["BACKEND"] = "django.core.cache.backends.redis.RedisCache"


# Celery
# https://docs.celeryq.dev/en/stable/django/first-steps-with-django.html

# Read by config/celery.py through config_from_object with namespace="CELERY",
# so the prefix is stripped: CELERY_BROKER_URL configures broker_url. Keeping
# them here rather than in celery.py means every connection URL in the project
# is read from the environment in exactly one file.
#
# The broker holds messages waiting to be consumed. The result backend holds
# return values after a task finishes. Both are Redis because Redis does both
# jobs adequately, but they are separate concerns on separate database numbers:
# see .env.example for why a queue purge must not be able to drop cached
# dashboard payloads.
CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="redis://redis:6379/0")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="redis://redis:6379/2")

# JSON only, in both directions. This is the setting that actually enforces
# "pass IDs to tasks, never model instances" (gotcha 3): with the default
# serializer a model instance would be pickled and shipped happily, arriving at
# the worker as a snapshot of a row that may since have changed. JSON refuses
# it outright with an EncodeError at enqueue time, in the process that has the
# stack trace worth reading.
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]

# Without this, a task that has been picked up by a worker is indistinguishable
# from one still sitting in the queue: both report PENDING, because PENDING
# really means "no state stored under this id". manage.py inspect_task_result
# exists to watch that transition, so it needs STARTED to be recorded.
CELERY_TASK_TRACK_STARTED = True

# Results are a debugging and polling aid, not a data store. An hour is long
# enough to inspect a task by id after the fact, short enough that Redis is not
# accumulating return values forever.
CELERY_RESULT_EXPIRES = timedelta(hours=1)

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True

# Celery 6 will stop retrying the initial broker connection by default and warns
# about it on every startup. Opting in now keeps the worker resilient to being
# started before Redis is accepting connections.
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True


# Embeddings
# https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2

# The model name and its output dimension are settings constants, not values
# hardcoded in onboarding/embeddings.py, so both live in one place. This does
# not make swapping providers a config change: the dimension is baked into
# Skill.embedding's VectorField at the database level, so a different model
# still needs a migration and a re-embed of every row.
EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"
EMBEDDING_DIMENSIONS = 384
