# Generated by Django 6.0.7 on 2026-08-03 18:40

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
    ]
