# Generated by Django 6.0.7 on 2026-08-03 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityevent',
            name='occurred_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='assessmentattempt',
            name='attempted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
