# Generated by Django 6.0.7 on 2026-08-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_alter_activityevent_occurred_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['-occurred_at'], name='activity_occurred_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['event_type', '-occurred_at'], name='activity_type_occurred_idx'),
        ),
    ]
