# Generated by Django 6.0.7 on 2026-08-06 18:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_activityevent_activity_occurred_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
