# Generated by Django 6.0.7 on 2026-08-07 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("onboarding", "0007_skill_embedding_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepartmentProgressSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("captured_on", models.DateField()),
                ("employee_count", models.PositiveIntegerField()),
                ("completion_percentage", models.FloatField()),
                ("activity_event_count", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ["-captured_on", "department__name"],
            },
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="passed",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assessmentattempt",
            name="scored_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="assessmentattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("passed__isnull", True), ("scored_at__isnull", True)),
                    models.Q(("passed__isnull", False), ("scored_at__isnull", False)),
                    _connector="OR",
                ),
                name="scored_at_and_passed_set_together",
            ),
        ),
        migrations.AddField(
            model_name="departmentprogresssnapshot",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="progress_snapshots",
                to="onboarding.department",
            ),
        ),
        migrations.AddConstraint(
            model_name="departmentprogresssnapshot",
            constraint=models.UniqueConstraint(
                fields=("department", "captured_on"), name="unique_department_snapshot_per_day"
            ),
        ),
    ]
